### PR TITLE
Update Readme as 0-0 is not top left but bottom left

### PR DESCRIPTION
**Pull request by Godzil**
There is also the fact that 0-0 is not the real bottom left, but the first row from the bottom and first left column, but I don't know if it is a bug or not.

### CODE REVIEW

**Comment by SteveAmor** [comment]
00-00 is the top left as far as I can tell.  So it's the following statement that is incorrect:

For example, both 01-02.png and 29x15.png are valid and will be placed on the second column, third row from the bottom, and 30th column, 16th row from the bottom respectively.

**Comment by Gadgetoid** [comment]
IM SO CONFUSED RIGHT NOW!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Godzil** [comment]
> Would it be less confusing to have 00, 00 being the middle?
Sounds a good idea, I would recommend it to be at a slightly random place

**Comment by domdavis** [comment]
And perhaps we should move to the Subnautica style co-ordinates, where it's `X`, `depth`, `Z` with `00`, `00`, `00` being the middle, sea level.

**Pull request merged**
