### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by domdavis**
I have resisted the temptation to continue my disbelief at`0`, `0` not being bottom right.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
You're the second person to rage at this. That's almost enough for a posse!

**Comment by Gadgetoid** [comment]
Maybe I should add a `use_cartesian` switch?

**Comment by domdavis** [comment]
My preference would be for cartesian to be the default and `--use_crazy_top_left_origin_because_I_am_insane` (or `-wtf` for the short code) to use the current system.

**Comment by archieroques** [comment]
See my latest PR, adding clear indication to the real `0, 0` that it is infact `0, 0`.

**Pull request merged**
